# Assignment 4
# Name: Digvijay Vikas Sawant
# PRN: 260240125023

'''
Q1.
1. Write a program to maintain student information. For each student store studid, name,
m1, m2 and m3 (marks of 3 subjects ). Accept information for 2 students and display it
as follows.
Student Details:
____________
Student Id
 Name: Divya
M1 : 78
M2: 86
M3: 89
'''

class Student:
    def __init__(self, sid=0,sname='',m1=0,m2=0,m3=0):
        self.__sid = sid
        self.__sname = sname
        self.__m1 = m1
        self.__m2 = m2
        self.__m3 = m3
    
    def set_sid(self, sid):
        self.__sid = sid
    
    def get_sid(self):
        return self.__sid
        
    def set_sname(self,snm):
        self.__sname = snm
    
    def get_sname(self):
        return self.__sname
    
    def set_m1(self,m):
        self.__m1 = m
    
    def get_m1(self):
        return self.__m1
    
    def set_m2(self,m):
        self.__m2 = m
    
    def get_m2(self):
        return self.__m2
    
    def set_m3(self,m):
        self.__m3 = m
    
    def get_m3(self):
        return self.__m3
          
    def __str__(self):
        return f''' 
    Id: {self.__sid}
    Name: {self.__sname}
    Marks 1: {self.__m1}
    Marks 2: {self.__m2}
    Marks 3: {self.__m3}
    '''


# Accept data for 2 students
students = []

for i in range(2):
    studid = input("Enter Student ID: ")
    name = input("Enter Name: ")
    m1 = int(input("Enter Marks M1: "))
    m2 = int(input("Enter Marks M2: "))
    m3 = int(input("Enter Marks M3: "))
    
    s = Student(studid, name, m1, m2, m3)
    students.append(s)

# Display
for s in students:
    print(s)


'''
2. Write a menu driven program to maintain student information. Modify Student class
created in previous assignment. Add a member gpa in student class, add a function in
student class to return GPA of a student
 calculateGPA()
 gpa=(1/3)*m1+(1/2)*m2+(1/4)*m3
Create an array to store Multiple students.
1. Display All Student
2. Search by id
3. Search by name
4. calculate GPA of a student
5. Exit
'''
class Student:
    def __init__(self, sid=0,sname='',m1=0,m2=0,m3=0):
        self.sid = sid
        self.sname = sname
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    
    def calculateGPA(self):
        return (1/3)*self.m1 + (1/2)*self.m2 + (1/4)*self.m3
    
    def display(self):
        print(self.sid, self.sname, self.m1, self.m2, self.m3)

students = []

n = int(input("Enter number of students: "))
for i in range(n):
    sid = input("Enter ID: ")
    name = input("Enter Name: ")
    m1 = int(input("M1: "))
    m2 = int(input("M2: "))
    m3 = int(input("M3: "))
    students.append(Student(sid, name, m1, m2, m3))


while True:
    print("\n1.Display All\n2.Search by ID\n3.Search by Name\n4.Calculate GPA\n5.Exit")
    choice = int(input("Enter choice: "))

    if choice == 1:
        for s in students:
            s.display()

    elif choice == 2:
        sid = input("Enter ID: ")
        for s in students:
            if s.sid == sid:
                s.display()

    elif choice == 3:
        name = input("Enter Name: ")
        for s in students:
            if s.sname == name:
                s.display()

    elif choice == 4:
        sid = input("Enter ID: ")
        for s in students:
            if s.sid == sid:
                print("GPA:", s.calculateGPA())

    elif choice == 5:
        break


'''
File handling and Object oriented programming
'''
'''
1. Design a system for XYZ Bank for storing account details, accounts may be joint
account or individual account,
Every account will have type either saving account or current account or demat
account
For every account interest rate and minimum balance need to be stored.
Interest rate for saving account is 4% and for current account 1%
Minimum balance for saving account will be 20000 and current account will be 1000
For each account store account holder details(fname, lname, mobile, email) id will
be autogenerated 3 letters of fname, 3letters of lname, count of account.
If it’s a saving account, then store chequebooknumber
If current account then store number of transactions/day, number of transactions
will be different for every account based on average annual balance in the account
and will keep on changing based on how customer maintains the balance in the
account.
For demat account store share details, for every share store name, number of
shares buying price, date of purchase, selling price, date of selling.
Store the information on of saving account in file savingac.txt, for current account in
currentac.txt and demat ac in dematac.txt
'''

class Account:
    count = 1

    def __init__(self, fname, lname, mobile, email):
        self.fname = fname
        self.lname = lname
        self.mobile = mobile
        self.email = email
        self.id = fname[:3] + lname[:3] + str(Account.count)
        Account.count += 1


class SavingAccount(Account):
    def __init__(self, fname, lname, mobile, email, cheque_no):
        super().__init__(fname, lname, mobile, email)
        self.interest = 4
        self.min_balance = 20000
        self.cheque_no = cheque_no

    def save(self):
        with open("savingac.txt", "a") as f:
            f.write(f"{self.id},{self.fname},{self.lname},{self.cheque_no}\n")


class CurrentAccount(Account):
    def __init__(self, fname, lname, mobile, email, transactions):
        super().__init__(fname, lname, mobile, email)
        self.interest = 1
        self.min_balance = 1000
        self.transactions = transactions

    def save(self):
        with open("currentac.txt", "a") as f:
            f.write(f"{self.id},{self.fname},{self.transactions}\n")


class DematAccount(Account):
    def __init__(self, fname, lname, mobile, email, shares):
        super().__init__(fname, lname, mobile, email)
        self.shares = shares

    def save(self):
        with open("dematac.txt", "a") as f:
            f.write(f"{self.id},{self.fname},{self.shares}\n")


s = SavingAccount("ABC", "abc", "99999", "abc@gmail.com", "CH123")
s.save()
c = CurrentAccount("XYZ", "xyz", "88888", "xyz@email.com", 50000)
c.save()


'''
Database connectivity
'''

'''
Q3.Write a program to store information about IPL teams in database
Create Team table to store teamid, tname, coachname and a player table to store
players (playerid,pname,speciality of player,teamid)
and perform following operations
1. add new Team
2. delete a team
3. delete a player from team(accept player id to delete)
4. display all batsman
5. display all player with a speciality(accept speciality from user)
6. add a new player in a team
7. modify coach of a team
8. exit
'''



'''
Q4.Do the following using Regular Expression:
accept lines from user and store in a list.
convert list into dictionary as follows
{
 “found”:[“this is algorithm”, “this is m” “mid”,”asdgfsdfasgfdmid”,”svdgahgmid”,],
“not found:[“this is data”,”this is min”]
}
store all lines ending with m or mid in a list and assign list to key “found” in
dictionary
otherwise store it in a list and assign it to key not found”
'''

import re

lines = []
n = int(input("Enter number of lines: "))

for i in range(n):
    line = input("Enter line: ")
    lines.append(line)

found = []
not_found = []

for line in lines:
    if re.search(r"(m|mid)$", line):
        found.append(line)
    else:
        not_found.append(line)

result = {
    "found": found,
    "not found": not_found
}

print(result)
